export const SIDE_NAVIGATION_WIDTH = 300;

export const SET_CATEGORIES = 'SET_CATEGORIES';

export const CATEGORIES_STORAGE_KEY = 'CATEGORIES_STORAGE_KEY';
export const SOURCES_STORAGE_KEY = 'SOURCES_STORAGE_KEY';

export const CUSTOMIZED_FEED_STORAGE_KEY = 'CUSTOMIZED_FEED_STORAGE_KEY';
